export const FETCH_USER_DETAIL = 'app/UserDetail/FETCH_USER_DETAIL';
export const SUCCEED_FETCH_USER_DETAIL = 'app/UserDetail/SUCCEED_FETCH_USER_DETAIL';
export const FAILED_FETCH_USER_DETAIL = 'app/UserDetail/FAILED_FETCH_USER_DETAIL';
export const FETCH_USER_REPOS = 'app/UserDetail/FETCH_USER_REPOS';
export const SUCCEED_FETCH_USER_REPOS = 'app/UserDetail/SUCCEED_FETCH_USER_REPOS';
export const FAILED_FETCH_USER_REPOS = 'app/UserDetail/FAILED_FETCH_USER_REPOS';
